In [ ]:
#Dmonstrate the working of SVM classifier for a suitable data set(e.g., iris dataset)

# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris

# Replace 'your_file_path.csv' with the actual path to your Iris dataset file
file_path = 'C:/Users/DELL/AI Lab/datasets/Iris.csv'

# Load the Iris dataset from the specified location
iris_data = pd.read_csv(file_path)

# Separate features (X) and target variable (y)
X = iris_data.iloc[:, :-1].values  # Features
y = iris_data.iloc[:, -1].values   # Target variable

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (SVM is sensitive to feature scaling)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the SVM classifier
svm_classifier = SVC(kernel='linear', random_state=42)  # Using a linear kernel

# Train the classifier
svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = svm_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
